### ISSUE TITLE
Hello, how to use it? I am not familiar with ruby, but I really need it.

### ISSUE THREAD

**Issue by Jolly23** [woodbusy/ooxml_decrypt#2]
How to use it? 
How can I run it in docker?
like "sudo docker run -it --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp ruby:2.3 ruby bin/decrypt_ooxml.rb"
Is "decrypt_ooxml.rb" is the entrance  of this Project?

I am not familiar with ruby, but I really need it.
Thank you.

**Comment by Jolly23** [comment]
Docker Hub's link is here:
https://hub.docker.com/_/ruby/

**Comment by timgentry** [comment]
With this now published as a RubyGem and updated documentation, the [README](https://github.com/woodbusy/ooxml_decrypt#readme) should tell you all you need to know to get it working

**Comment by timgentry** [comment]
@woodbusy do you want to close this issue, I can't?
